[package]
name = "slowfetch"
version = "0.2.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = true  # Link Time Optimization
debug = false
codegen-units = 1  # Reduce the number of codegen units for more optimization
panic = "abort"

[dependencies]
inkline = "1.0"
tintify = "1.0"
